// sceLibFont uses original system fonts decoded by scripts/prepare_fonts.py.
// No replacement glyphs or guessed metrics are generated by the runtime.
#include "kernel.hpp"

#include <algorithm>
#include <array>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <iostream>
#include <iterator>
#include <map>
#include <set>

namespace pspweb {
namespace {
constexpr std::uint32_t kInvalidLib = 0x80460002u, kInvalidParameter = 0x80460003u;
struct Glyph {
    std::array<std::uint8_t, 60> info{};
    std::vector<std::uint8_t> pixels;
};
struct Font {
    std::array<std::uint8_t, 264> info{};
    std::map<std::uint32_t, Glyph> glyphs;
};
struct FontState {
    std::vector<Font> fonts;
    std::set<std::uint32_t> libraries;
    struct OpenFont { std::uint32_t library{}, index{}; };
    std::map<std::uint32_t, OpenFont> open;
};

std::uint32_t word(const std::uint8_t *p) {
    return p[0] | (std::uint32_t(p[1]) << 8u) | (std::uint32_t(p[2]) << 16u) | (std::uint32_t(p[3]) << 24u);
}

bool load_font(const std::filesystem::path &path, Font &font) {
    std::ifstream input(path, std::ios::binary);
    if (!input) return false;
    std::vector<std::uint8_t> bytes((std::istreambuf_iterator<char>(input)), {});
    if (bytes.size() < 272u || std::memcmp(bytes.data(), "PWF1", 4) != 0) return false;
    const std::uint32_t count = word(bytes.data() + 4u);
    if (count > 65536u) return false;
    std::copy_n(bytes.begin() + 8, 264, font.info.begin());
    std::size_t cursor = 272u;
    for (std::uint32_t i = 0; i < count; ++i) {
        if (cursor + 68u > bytes.size()) return false;
        const std::uint32_t code = word(bytes.data() + cursor);
        Glyph glyph;
        std::copy_n(bytes.begin() + cursor + 4u, 60, glyph.info.begin());
        const std::uint32_t size = word(bytes.data() + cursor + 64u);
        cursor += 68u;
        if (size > 127u * 127u || cursor + size > bytes.size() ||
            size != word(glyph.info.data()) * word(glyph.info.data() + 4u)) return false;
        glyph.pixels.assign(bytes.begin() + cursor, bytes.begin() + cursor + size);
        cursor += size;
        font.glyphs.emplace(code, std::move(glyph));
    }
    return cursor == bytes.size();
}

Font *opened(FontState &state, std::uint32_t handle) {
    const auto it = state.open.find(handle);
    return it == state.open.end() ? nullptr : &state.fonts[it->second.index];
}

void copy_guest(psprecomp::GuestMemory &m, std::uint32_t address, const std::uint8_t *data, std::size_t size) {
    for (std::size_t i = 0; i < size; ++i) m.store8(address + static_cast<std::uint32_t>(i), data[i]);
}
} // namespace

void Kernel::install_fonts() {
    auto state = std::make_shared<FontState>();
    fonts_ = state;
    const char *directory = std::getenv("PSPWEB_FONT_DIR");
    const std::filesystem::path root = directory ? directory : "/game/fonts";
    std::vector<std::string> names{"jpn0"};
    for (int i = 0; i < 16; ++i) names.push_back("ltn" + std::to_string(i));
    for (const auto &name : names) {
        Font font;
        if (load_font(root / (name + ".pwf"), font)) state->fonts.push_back(std::move(font));
    }
    if (!state->fonts.empty()) std::cout << "[font] loaded " << state->fonts.size() << " original system fonts\n";
    auto &m = rt_.memory();
    auto add = [this](std::uint32_t nid, const char *name, std::function<std::uint32_t(Ctx &)> body) {
        rt_.register_hle("sceLibFont", nid, [body](psprecomp::Runtime &, Ctx &ctx) { finish(ctx, body(ctx)); });
        rt_.nids().add("sceLibFont", nid, name);
        char key[40];
        std::snprintf(key, sizeof key, "sceLibFont:0x%08X", nid);
        registered_.insert(key);
    };
    add(0x67F17ED7u, "sceFontNewLib", [this, state, &m](Ctx &ctx) {
        const std::uint32_t id = static_cast<std::uint32_t>(new_uid());
        state->libraries.insert(id);
        if (ctx.gpr[5]) m.store32(ctx.gpr[5], 0u);
        return id;
    });
    add(0x574B6FBCu, "sceFontDoneLib", [state](Ctx &ctx) {
        state->libraries.erase(ctx.gpr[4]);
        for (auto it = state->open.begin(); it != state->open.end();)
            if (it->second.library == ctx.gpr[4]) it = state->open.erase(it); else ++it;
        return 0u;
    });
    add(0x27F6E642u, "sceFontGetNumFontList", [state, &m](Ctx &ctx) {
        const bool valid = state->libraries.contains(ctx.gpr[4]);
        if (ctx.gpr[5]) m.store32(ctx.gpr[5], valid ? 0u : kInvalidLib);
        return valid ? static_cast<std::uint32_t>(state->fonts.size()) : 0u;
    });
    add(0xBC75D85Bu, "sceFontGetFontList", [state, &m](Ctx &ctx) {
        if (!state->libraries.contains(ctx.gpr[4])) return kInvalidLib;
        const std::size_t count = std::min<std::size_t>(ctx.gpr[6], state->fonts.size());
        for (std::size_t i = 0; i < count; ++i)
            copy_guest(m, ctx.gpr[5] + static_cast<std::uint32_t>(i * 168u), state->fonts[i].info.data() + 92u, 168u);
        return 0u;
    });
    add(0xA834319Du, "sceFontOpen", [this, state, &m](Ctx &ctx) {
        const bool valid = state->libraries.contains(ctx.gpr[4]) && ctx.gpr[5] < state->fonts.size();
        if (ctx.gpr[7]) m.store32(ctx.gpr[7], valid ? 0u : kInvalidParameter);
        if (!valid) return 0u;
        const std::uint32_t id = static_cast<std::uint32_t>(new_uid());
        state->open[id] = {ctx.gpr[4], ctx.gpr[5]};
        return id;
    });
    add(0x3AEA8CB6u, "sceFontClose", [state](Ctx &ctx) { state->open.erase(ctx.gpr[4]); return 0u; });
    add(0x0DA7535Eu, "sceFontGetFontInfo", [state, &m](Ctx &ctx) {
        const auto *font = opened(*state, ctx.gpr[4]);
        if (!font || !ctx.gpr[5]) return kInvalidParameter;
        copy_guest(m, ctx.gpr[5], font->info.data(), font->info.size());
        return 0u;
    });
    add(0xDCC80C2Fu, "sceFontGetCharInfo", [state, &m](Ctx &ctx) {
        const auto *font = opened(*state, ctx.gpr[4]);
        if (!font || !ctx.gpr[6]) return kInvalidParameter;
        const auto glyph = font->glyphs.find(ctx.gpr[5] & 0xFFFFu);
        const std::array<std::uint8_t, 60> empty{};
        copy_guest(m, ctx.gpr[6], glyph == font->glyphs.end() ? empty.data() : glyph->second.info.data(), 60u);
        return 0u;
    });
    add(0x980F4895u, "sceFontGetCharGlyphImage", [this, state, &m](Ctx &ctx) {
        const auto *font = opened(*state, ctx.gpr[4]);
        if (!font || !ctx.gpr[6]) return kInvalidParameter;
        const auto found = font->glyphs.find(ctx.gpr[5] & 0xFFFFu);
        if (found == font->glyphs.end()) return 0u;
        const auto &glyph = found->second;
        const std::uint32_t image = ctx.gpr[6], format = m.load32(image);
        if (format != 0u && format != 2u) return 0u;
        const std::int32_t x64 = static_cast<std::int32_t>(m.load32(image + 4u));
        const std::int32_t y64 = static_cast<std::int32_t>(m.load32(image + 8u));
        const int origin_x = x64 >> 6, origin_y = y64 >> 6, fraction = x64 & 63;
        const int width = static_cast<int>(word(glyph.info.data())), height = static_cast<int>(word(glyph.info.data() + 4));
        const int buffer_width = m.load16(image + 12u), buffer_height = m.load16(image + 14u);
        const std::uint32_t stride = m.load16(image + 16u), buffer = m.load32(image + 20u);
        if (!buffer || !width || !height) return 0u;
        ge_worker_->call([this, buffer, stride, buffer_height] {
            ge_->prepare_cpu_write(buffer, stride * static_cast<std::uint32_t>(buffer_height));
        });
        const auto sample = [&glyph, width, height](int x, int y) {
            return x < 0 || x >= width || y < 0 || y >= height ? 0 : int(glyph.pixels[y * width + x]);
        };
        const int scale = format == 0u ? 1 : 17;
        for (int y = 0; y < height; ++y) {
            if (origin_y + y < 0 || origin_y + y >= buffer_height) continue;
            for (int x = 0; x < width + (fraction != 0); ++x) {
                const int dest_x = origin_x + x;
                if (dest_x < 0 || dest_x >= buffer_width) continue;
                const int ink = sample(x - 1, y) * scale * fraction / 64 +
                    (sample(x, y) * scale * (64 - fraction) + 63) / 64;
                const std::uint32_t address = buffer + (origin_y + y) * stride + (format == 0u ? dest_x / 2 : dest_x);
                const int old = m.load8(address);
                if (format == 0u) {
                    const int shift = (dest_x & 1) * 4;
                    const int value = std::min(15, ((old >> shift) & 15) + ink);
                    m.store8(address, static_cast<std::uint8_t>((old & ~(15 << shift)) | (value << shift)));
                } else m.store8(address, static_cast<std::uint8_t>(std::min(255, old + ink)));
            }
        }
        return 0u;
    });
}
} // namespace pspweb
