const assert = require('node:assert/strict');
const Input = require('../profile/web/input.js');
const input = new Input('fps');
input.key('KeyW', true);
assert.deepEqual(input.sample(), {buttons:0,lx:128,ly:1});
input.key('KeyS', true);
assert.equal(input.sample().ly,128);
input.key('KeyS',false);
input.clear();
assert.deepEqual(input.sample(), {buttons:0,lx:128,ly:128});
input.key('Enter',true);
assert.equal(input.sample().buttons,0x4000);
input.key('Enter',false);
assert.equal(input.sample().buttons,0);
const pad = {connected:true,axes:[0.1,-0.1,0.8,-0.8],buttons:Array.from({length:16},()=>({pressed:false,value:0}))};
pad.buttons[6].value=.8; pad.buttons[7].value=.8;
assert.deepEqual(input.sample([pad]),{buttons:0x2000|0x1000|0x100|0x200,lx:128,ly:128});
pad.axes=[0,0,0,0]; pad.buttons[6].value=pad.buttons[7].value=0;
assert.deepEqual(input.sample([pad]),{buttons:0,lx:128,ly:128});
input.setProfile('psp'); input.key('KeyW',true);
assert.deepEqual(input.sample(),{buttons:0x200,lx:128,ly:128});
input.clear(); input.key('KeyI',true);
assert.equal(input.sample().ly,1);
console.log('Keyboard release, neutral sticks, triggers, right-stick aiming: passed');
